version: '3.10'


services:
  web:
    build: .
    ports:
      - 5000:5000
    # depends_on:
    #   - mongo
    env_file:
      - .env
    environment:
      - APP_NAME=townsnet_api
      - APP_VERSION=dev
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: /start-reload.sh